ollama:
  gemma3_4b: gemma3:4b
  qwen3_4b: qwen3:4b
  qwen3_06b: qwen3:0.6b
  temperature: 0.7
  num_predict: 4096

qwen:
  turbo: qwen-turbo
  temperature: 0.7
  max_tokens: None
  timeout: None
  max_retries: 3
  base_url: https://dashscope.aliyuncs.com/compatible-mode/v1
  organization: None